---
functional:
  - Возможность регистрации на сайте с пощью почты
  - Возможность авторизации через Github
  - Возможность авторизации чере Discord 
  - Возможность создания игры с выбором параметров (Уровень, тип игры, время игры, тип задачи)
  - Возможность просмотра таблица лидеров (По недели, месяцу, всем пользователям) 
  - Возможность поиска определённого пользователя в таблице лидеров
  - Можно вступить в баттл с игроком или ботом
  - Возможность общаться в общем чате
  - Возможность организации турниров  
  - Возможность просмотра баттла зрителем
  - Задачи можно перевести на Английский или Русский язык
  - Возможность посмотреть повтор по завершённой игре 
  - Возможность просмотра списка завершённых игр
  - В чате отображается список пользователей который онлайн в данный момент
  - Возможность писать в чат во время баттла
  - Возможность сдаться во время баттла
  - Возможность проверки решения во время баттла
  - Возможность переключения темы редактора во время баттла на светлую или тёмную 
  - Возможность просмотра профиля игрока на отдельной странице 
  - Пользователь может перейти в настройки своего профиля и менять параметры (Name, weapon, sound type, sound level)
  - Возможность выбора языка программирования во время баттла 
  - Участник баттла имеет возможность переподключения к баттлу 
  - Пользователю, который находися на сайте онлайн, можно отправить инвайт на баттл
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Возможность просматривать игры будучи не авторизованным
  - Возможность выбора языка на сайте (Русский, Английский)