---
functional:
  - Возможность регистрации на сайте
  - Возможность авторизации через GitHub
  - Возможность авторизации чере Discord
  - Возможность создания игры с выбором параметров (Уровень, тип игры, время игры, тип задачи)
  - Возможность просмотра таблица лидеров (По недели, месяцу, общую)
  - Возможность поиска определённого пользователя в таблице лидеров
  - Можно вступить в баттл с игроком или ботом
  - Возможность общаться в общем чате 
  - Возможность организации турниров
  - Возможность просмотра баттла зрителем
  - Задачи можно перевести на Английский или Русский язык
  - Завершённую игру можно посмотреть в записи
  - Возможность просмотра списка завершённых игр
  - В чате отображается список пользователей который онлайн в данный момент
  - Возможность писать в чат во время баттла
  - Возможность сдаться во время баттла
  - Возможность проверки решения во время баттла
  - Возможность переключения темы во время баттла на светлую или тёмную
  - Есть возможность переключения вкладок на главной странице (Lobby, tournaments, completed games)
  - Возможность просмотра профиля игрока 
  - Пользователь может перейти в настройки своего профиля и менять параметры (Name, weapon, sound type, sound level)
  - Возможность выбора языка программирования во время баттла
  - Участник баттла имеет возможность переподключения к баттлу
  - После окончания баттла можно остаться на странице баттла
  - Пользователю, который находися на сайте онлайн, можно отправить инвайт на баттл
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Возможность просматривать игры будучи не авторизованным
  - Возможность выбора языка на сайте (Русский, Английский)


